### ISSUE TITLE
puppetdb: issue if host does not resolve to puppetdb

### ISSUE THREAD

**Issue by spali** [Icinga/puppet-icingaweb2#197] opened 2017-12-13 13:27 UTC
not sure if this is an issue of `puppet-icingaweb2` or the `icingaweb2-module-puppetdb` itself.
But configured the puppetdb with defaults from `puppetlabs-puppetdb` module on the same host as icinga and used `puppet-icingaweb2` with
```
        class {'::icingaweb2::module::puppetdb':
                git_revision    => $puppetdb_version,
                ssl             => 'puppet',
        }
```
this copies the ssl certs with the dir name `puppetdb` in to the ssl dir.
if I have interpreted the code of icingaweb2-module-puppetdb right, the import source puppetdb server list gets the name from the dir name and tries to connect to `puppetdb` host. But this should be the `$::fqdn` of my puppetdb server which is in my case the same as the icinga server.

error thrown when selected the "wrong" `puppetdb` host in the import source server list:
```
Failed to load resource types: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

when I add `puppetdb` to the `hosts` file, it tries to connect, but get's an ssl cert error, because the CN of the cert is my `$::fqdn` of my puppetdb host and not `puppetdb`.

Don' know if `puppet-icingaweb2` should change the dirname to the `$::fqdn` of the puppetdb host or if probably `icingaweb2-module-puppetdb` should change it's logic and get's the hostname from the CN of the cert itself.

**Comment by spali** [comment] 2017-12-13 16:57
the following change did work for me, not sure if this is the right way.
```diff
@@ -48,7 +48,7 @@ class icingaweb2::module::puppetdb(
     'puppet': {

       $my_certname     = $::fqdn
-      $puppetdb_ssldir = "${ssl_dir}/puppetdb"
+      $puppetdb_ssldir = "${ssl_dir}/${my_certname}"

       file { [$puppetdb_ssldir, "${puppetdb_ssldir}/private_keys", "${puppetdb_ssldir}/certs"]:
         ensure  => 'directory',
```

**Comment by bobapple** [comment] 2017-12-29 13:54
It looks like you're not providing any certificates in your `::icingaweb2::module::puppetdb'` declaration.

Here's an example:

``` puppet
include icingaweb2

class {'::icingaweb2::module::puppetdb':
  git_revision => 'master',
  ssl          => 'none',
  certificates => {
    puppetdb1 => {
      ssl_key    => '-----BEGIN RSA PRIVATE KEY----- abc...',
      ssl_cacert => '-----BEGIN RSA PRIVATE KEY----- def...',
    }
  }
}
```

Where `puppetdb1` is the hostname of your PuppetDB. This creates the directories and files that icingaweb2-module-puppetdb expects.

**Comment by bobapple** [comment] 2018-01-03 14:17
Basically, the problem is that if you choose to use `puppet` for the `ssl` parameter, you have no to set the hostname of the server where PuppetDB is running.

Setting this to the `$::fqdn` solves the issue in your case, but the general problem remains. A common case is that the PuppetDB runs on a different host and you want to use your hosts Puppet certificates to connect to it.

The `puppet` option for the `ssl` parameter seems pretty useless right now.

One workaround is to use the `certificates` hash, however you would need to copy the certificates to your puppet code.

To fix this in general we should think of changing this class a little. It should be possible to add one or multiple PuppetDB servers. For each server it must be possible to use either the Puppet certificates of the Icinga Web 2 server or custom certificates. We need to be careful with these changes because they would break the current behaviour. Probably the only option is to add new settings and just deprecate the current options.

@rgevaert what do you think?

**Comment by spali** [comment] 2018-01-03 15:12
Thats true.
From my side no hurry. To be honest I dropped the puppetdb director module in favor of using puppetdb_query in Puppet directly to generate the icinga configuration without director for puppet managed nodes.

**Comment by bobapple** [comment] 2018-01-03 15:22
@spali That's a little off topic, but do you have an example for that somewhere? I just would like to see how this works.

**Comment by spali** [comment] 2018-01-03 15:55
Not sure in which version puppetdb_query was introduced, but there is also a module available with a different query syntax, which should do almost the same (but never tried by myself).

First query gets all nodes.
second query is for getting the parameters I used in the my profile class for icinga which includes all the zone information which I set on the icinga host. Also I put the facts I got in the first query to the vars of the icinga host object.

One disadvantage is, it requires a puppet run on the icinga host for parameter changes (or for the initial setup) in the class profile::icinga and then one on the icinga master to generate the configuration.
Using the director with the puppetdb module would save the puppet run on the icinga master.

Here the essential part of my manifest for the icinga master:
```puppet

  # get all known puppet nodes
  puppetdb_query('inventory {}')
  .each |$node| {

    $result = puppetdb_query(sprintf_hash('resources [parameters] { type = "Class" and title = "Profile::Icinga" and certname = "%<certname>s" }', { certname => $node['certname'] }))
    if (length($result) > 0) { # exclude node which didn't apply icinga profile yet
      $icinga_params = $result[0]['parameters'] # extract parameter hash from result array
    }

    if ($icinga_params != undef) {
      $zone = $icinga_params["local_zone_name"]
      $command_endpoint = $node['certname']

      $host_vars = deep_merge(pick($icinga_params['host_vars'], {}), {
        facts    => {
          kernel           => $node['facts']['kernel'],
          kernelversion    => $node['facts']['kernelversion'],
          kernelrelease    => $node['facts']['kernelrelease'],
          kernelmajversion => $node['facts']['kernelmajversion'],
          is_virtual       => $node['facts']['is_virtual'],
          virtual          => $node['facts']['virtual'],
          os               => "-:${icinga_format_hash($node['facts']['os'], false)}",
        },
      })

      # create all host objects
      ::icinga2::object::host { $node['certname']:
        import           => [ 'generic-host', "os_family_${downcase($node['facts']['os']['family'])}" ],
        display_name     => $node['certname'],
        address          => $node['facts']['ipaddress'],
        address6         => $node['facts']['ipaddress6'],
        zone             => $zone_name,
        command_endpoint => $command_endpoint,
        vars             => $host_vars,
        target           => "${confd}/objects/${$node['certname']}.conf",
      }
    }
  }
```

**Comment by spali** [comment] 2018-01-03 16:06
forgot to say (not included in the above example):
I use queries also for getting i.e. apache puppet class and its configuration and set this in a services dictionary on the host which is then used by an "apply Service" object.
```
vars = {
  facts = {....}
  services = {
    http => { # settings from the puppetdb query of the apache class
    }
  }
```

**Comment by Thomas-Gelf** [comment] 2018-01-03 16:28
@bobapple: problem here is that this module hard-codes the PuppetDB hostname to `puppetdb` in [puppetdb.pp on line 51](https://github.com/Icinga/puppet-icingaweb2/blob/cbb37f8/manifests/module/puppetdb.pp#L51) while the related [example](https://github.com/Icinga/icingaweb2-module-puppetdb/blob/master/doc/01-Installation.md#puppet-based-configuration) shows that this should be a `${puppetdb_host}`.

Cheers,
Thomas

OT, regarding `puppetdb_query()`: it's available since a very long time, used to be a community contribution for the very first PuppetDB releases. Changed a bit since then. I've seen quite some setups using `puppetdb_query()` in a loop, formerly mostly using `generate_resources()`. With Icinga 2 agents in place it works fine once you REALLY understood Icinga 2 Clustering.

A ton of `nagios_*` objects used to kill you at Icinga 1 times. Solution was passing the result of the query to a custom function rendering all hosts/services to a single dedicated file resource. This helped me to reduce Icinga master catalog run times from 40 minutes to 14 seconds in a customer setup at the time being :laughing:

@spali: Said this, dealing with a ton of files will kill you sooner or later, so depending on the amount of hosts this is something I'd tune in the shown example. With our `puppet-icinga2` module this should be easy to accomplish I guess. The rest is fine, but of course a lot of complexity is still missing - as there is no service and no threshold involved. In largish setups it can easily become an unmaintainable mess when you try to parameterize every single check threshold via Hiera or similar. One more issue with the shown example: if I didn't misread it, you're deploying host checks in a way telling every single host to ping himself. Is there a good reason for doing so?

In case you're still interested in resolving the initial issue, changing the name of the deployed ssl folder should fix this for you. Using Director in Puppet environments is an enormous help, as it brings in a lot of transparency. Who suffered the pain of debugging PuppetDB without expert knowledge usually loves it. But I'm opinionated of course, as I wrote that module.

Last hint: I'm using lightweight custom defined resource types to let Puppet tell my Director what hosts to deploy. In such a setup they are easier to handle and import rather than `::icinga2::object::host` objects or `nodes` fetched from the PuppetDB. Apply rules ship the vast majority of the checks, Hiera users or module writers can throw in custom services to the mix with one more dedicated resource type. That way I usually try to restrict them to a) choosing a service template, b) a service name and c) related vars. Users with such permissions are often also able to also add single services to only their own hosts in Director. Nice feature: granted enough permissions they can override thresholds from apply rules for single hosts at any time. Otherwise you get mad explaining them how to change the threshold for a specific disk check deployed via Puppet.

Keeping Service Templates in Director and artificially restricting PuppetDB import to "choose template names and vars" has one more big advantage: your users cannot combine weird operations, select check commands you didn't expect them to use or do weird things with `command_endpoint` or `zone` settings (without really understanding the consequences of those choices).

Regards,
Thomas

**Comment by rgevaert** [comment] 2018-01-03 16:48
@bobapple I agree with you that there is a bug I introduced.  I think that adding a parameter to pass the puppetdb hostname would also be a good fix.  I'm using only the certificates hash as that is what I need to connect to multiple puppetdb servers.

**Comment by spali** [comment] 2018-01-03 17:00
@Thomas-Gelf 
Thanks for your input. I just started to setup this for a small environment with around 15-20 nodes.
Till now it works quite good. But your're right with all your points.
Regarding pinging host itself, that's something on my todo list to change *shame on me* ;) And set the command_endpoint in the "apply Service" rule.

The idea behind generating the host configuration directly in puppet was to keep it a bit more simple without also introduce syncing in director (for such a small environment I tried to prevent this additional complexity). Not sure if this is a good or bad idea for a small environment, especially because the time will come where I anyway want to import other information's from somewhere else.
Currently my plan was to drop the ::icinga2::object::host in favor of just generate the icinga hosts.conf with puppet and a template. But I like your approach (if I understood you right) to use "dummy" defined resources just to tell the director what to deploy. Sounds like a really clean and "interface" between puppet and icinga.

**Comment by Thomas-Gelf** [comment] 2018-01-03 17:09
@spali: you absolutely understood it right. There is no "best" way of doing it, you have to figure out the lesser evil for your use-case. In every scenario all you get from us are just building blocks. It's up to you to combine them in a meaningful way. Try to stay pragmatic, keep things simple and focus on making your life easier. When it feels like Puppet and Icinga are working for you (and not the other way round) then you're on the right path ;-)

**Closed** 2018-01-04 15:41 UTC
Labels: bug
